In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [3]:
df = pd.read_csv("../data/Nassau Candy Distributor.csv")

In [4]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [5]:
df.shape

(10194, 18)

In [6]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  str
 3   Ship Date       10194 non-null  str
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), str(12)
memory usage: 2.9 MB

In [8]:
df.describe()

,Row ID,Customer ID,Sales,Units,Gross Profit,Cost
count,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,134468.961154,13.908537,3.791838,9.166451,4.742087
std,2942.898656,20231.483007,11.341020,2.228317,6.643740,5.061647
min,1.000000,100006.000000,1.250000,1.000000,0.250000,0.600000
25%,2549.250000,117212.000000,7.200000,2.000000,4.900000,2.400000
50%,5097.500000,133550.000000,10.800000,3.000000,7.470000,3.600000
75%,7645.750000,152051.000000,18.000000,5.000000,12.250000,5.700000
max,10194.000000,192314.000000,260.000000,14.000000,130.000000,130.000000

In [9]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df_clean = df.copy()

In [12]:
df_clean.dtypes

Row ID              int64
Order ID              str
Order Date            str
Ship Date             str
Ship Mode             str
Customer ID         int64
Country/Region        str
City                  str
State/Province        str
Postal Code           str
Division              str
Region                str
Product ID            str
Product Name          str
Sales             float64
Units               int64
Gross Profit      float64
Cost              float64
dtype: object

In [14]:
df_clean["Order Date"] = pd.to_datetime(
    df_clean["Order Date"],
    format="%d-%m-%Y"
)

df_clean["Ship Date"] = pd.to_datetime(
    df_clean["Ship Date"],
    format="%d-%m-%Y"
)

In [15]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  datetime64[us]
 3   Ship Date       10194 non-null  datetime64[us]
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: datetime64[us](2), float64(3), int64(3), str(10)
memory usage: 2.7 MB

In [16]:
df_clean["Lead Time"] = (
    df_clean["Ship Date"] -
    df_clean["Order Date"]
).dt.days

In [17]:
df_clean.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Lead Time
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912

In [18]:
df_clean["Lead Time"].describe()

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Lead Time, dtype: float64

In [19]:
df_clean[df_clean["Lead Time"] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Country/Region, City, State/Province, Postal Code, Division, Region, Product ID, Product Name, Sales, Units, Gross Profit, Cost, Lead Time]
Index: []

In [20]:
df_clean["Order Year"] = df_clean["Order Date"].dt.year
df_clean["Order Month"] = df_clean["Order Date"].dt.month
df_clean["Order Day"] = df_clean["Order Date"].dt.day
df_clean["Order Weekday"] = df_clean["Order Date"].dt.day_name()

In [21]:
df_clean = df.copy()

In [22]:
df_clean.dtypes

Row ID              int64
Order ID              str
Order Date            str
Ship Date             str
Ship Mode             str
Customer ID         int64
Country/Region        str
City                  str
State/Province        str
Postal Code           str
Division              str
Region                str
Product ID            str
Product Name          str
Sales             float64
Units               int64
Gross Profit      float64
Cost              float64
dtype: object

In [26]:
df_clean["Order Date"] = pd.to_datetime(
    df_clean["Order Date"],
    dayfirst=True
)

df_clean["Ship Date"] = pd.to_datetime(
    df_clean["Ship Date"],
    dayfirst=True
)

In [27]:
df_clean[["Order Date", "Ship Date"]].head(10)

  Order Date  Ship Date
0 2024-01-03 2026-06-30
1 2024-01-04 2026-07-01
2 2024-01-04 2026-07-01
3 2024-01-04 2026-07-01
4 2024-01-05 2026-07-05
5 2024-01-06 2026-07-03
6 2024-01-06 2026-07-03
7 2024-01-06 2026-06-30
8 2024-01-06 2026-07-03
9 2024-01-06 2026-07-03

In [28]:
df_clean.dtypes

Row ID                     int64
Order ID                     str
Order Date        datetime64[us]
Ship Date         datetime64[us]
Ship Mode                    str
Customer ID                int64
Country/Region               str
City                         str
State/Province               str
Postal Code                  str
Division                     str
Region                       str
Product ID                   str
Product Name                 str
Sales                    float64
Units                      int64
Gross Profit             float64
Cost                     float64
dtype: object

In [29]:
df_clean["Lead Time"] = (
    df_clean["Ship Date"] -
    df_clean["Order Date"]
).dt.days

In [30]:
df_clean.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Lead Time
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,909
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,909
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,909
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,909
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,912

In [31]:
df_clean["Lead Time"].describe()

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: Lead Time, dtype: float64

In [32]:
df_clean[df_clean["Lead Time"] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Country/Region, City, State/Province, Postal Code, Division, Region, Product ID, Product Name, Sales, Units, Gross Profit, Cost, Lead Time]
Index: []

In [33]:
df_clean["Order Year"] = df_clean["Order Date"].dt.year

df_clean["Order Month"] = df_clean["Order Date"].dt.month

df_clean["Order Day"] = df_clean["Order Date"].dt.day

df_clean["Order Weekday"] = df_clean["Order Date"].dt.day_name()

In [35]:
import os
os.getcwd()

'c:\\Users\\Radhika U R\\OneDrive\\Desktop\\Factory Reallocation System\\Notebooks'

In [36]:
df_clean.to_csv("../data/cleaned_data.csv", index=False)

In [37]:
import os

os.listdir("../data")

['cleaned_data.csv', 'Nassau Candy Distributor.csv']

# Exploratory Data Analysis (EDA)

In [38]:
df = pd.read_csv("../data/cleaned_data.csv")

In [39]:
import matplotlib.pyplot as plt
import plotly.express as px

In [40]:
df.shape

(10194, 23)

In [41]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost', 'Lead Time', 'Order Year',
       'Order Month', 'Order Day', 'Order Weekday'],
      dtype='str')

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  str
 3   Ship Date       10194 non-null  str
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
 18  Lead Time       10194 non-null  int64
 19  Order Year      10194 non-null  int64
 20  Order Month     10194 non-null  int64
 21  Order Day       10194 non-null  int64
 22  Order Weekday   10194 non-null  str
dtypes: float64(3), int64(7), str(13)
memory usage: 3.4 MB

Business KPI Dashboard

In [43]:
print("Total Sales :", df["Sales"].sum())
print("Total Profit :", df["Gross Profit"].sum())
print("Total Orders :", df["Order ID"].nunique())
print("Total Products :", df["Product Name"].nunique())
print("Average Lead Time :", df["Lead Time"].mean())

Total Sales : 141783.63
Total Profit : 93442.79999999999
Total Orders : 8549
Total Products : 15
Average Lead Time : 1320.8418677653522

Sales by Division

In [44]:
division_sales = (
    df.groupby("Division")["Sales"]
      .sum()
      .sort_values(ascending=False)
)

division_sales

Division
Chocolate    131692.90
Other          9663.25
Sugar           427.48
Name: Sales, dtype: float64

In [45]:
fig = px.bar(
    division_sales,
    title="Sales by Division",
    labels={"value": "Sales", "Division": "Division"}
)

fig.show()

## Insight

- Chocolate division generates the highest sales.
- Sugar division contributes the least revenue.
- The company should focus on expanding chocolate products while improving the sales strategy for the sugar division.

Top 10 Products by Sales

In [46]:
top_products = (
    df.groupby("Product Name")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_products

Product Name
Wonka Bar - Triple Dazzle Caramel    28485.00
Wonka Bar -Scrumdiddlyumptious       27874.80
Wonka Bar - Milk Chocolate           26867.75
Wonka Bar - Fudge Mallows            24890.40
Wonka Bar - Nutty Crunch Surprise    23574.95
Lickable Wallpaper                    7860.00
Kazookles                             1205.75
Wonka Gum                              597.50
Everlasting Gobstopper                 130.00
Fizzy Lifting Drinks                    78.75
Name: Sales, dtype: float64

Top 10 Products on sale

In [47]:
fig = px.bar(
    top_products,
    title="Top 10 Products by Sales"
)

fig.show()

## Insight

- Wonka Bar – Triple Dazzle Caramel is the highest-selling product.
- Most of the top-selling products belong to the Chocolate division.
- These products should be prioritized for production and inventory planning.

Sales by Region

In [48]:
region_sales = (
    df.groupby("Region")["Sales"]
      .sum()
      .sort_values(ascending=False)
)

fig = px.pie(
    values=region_sales.values,
    names=region_sales.index,
    title="Sales Distribution by Region"
)

fig.show()

## Insight

- Pacific region contributes the highest sales.
- Gulf region contributes the lowest sales.
- The company should investigate demand in the Gulf region and improve its market presence.

Profit by Division

In [49]:
profit = (
    df.groupby("Division")["Gross Profit"]
      .sum()
      .sort_values(ascending=False)
)

fig = px.bar(
    profit,
    title="Profit by Division"
)

fig.show()

## Insight

- Chocolate division contributes the highest profit.
- Sugar division generates minimal profit.
- Chocolate products should remain the company's primary focus for maximizing profitability.

Ship Mode Usage

In [50]:
ship_mode = (
    df.groupby("Ship Mode")
      .size()
      .sort_values(ascending=False)
)

ship_mode

Ship Mode
Standard Class    6120
Second Class      1979
First Class       1548
Same Day           547
dtype: int64

In [51]:
fig = px.bar(
    ship_mode,
    title="Orders by Ship Mode"
)

fig.show()

## Insight

- Standard Class is the most frequently used shipping method.
- Same Day shipping is used the least.
- Most customers prefer economical shipping over faster delivery options.

Average Lead Time by Region

In [52]:
lead_time = (
    df.groupby("Region")["Lead Time"]
      .mean()
      .sort_values(ascending=False)
)

lead_time

Region
Interior    1323.091221
Atlantic    1322.745144
Pacific     1322.194897
Gulf        1311.374691
Name: Lead Time, dtype: float64

In [53]:
fig = px.bar(
    lead_time,
    title="Average Lead Time by Region"
)

fig.show()

## Insight

- The average lead time is almost the same across all regions.
- No region experiences significantly higher delivery delays.
- This indicates a consistent shipping performance throughout the distribution network.

Top 10 Cities by Sales

In [54]:
city_sales = (
    df.groupby("City")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

city_sales

City
New York City    12514.90
Los Angeles      10408.75
Philadelphia      7415.52
San Francisco     7018.61
Seattle           5893.39
Houston           5429.41
Chicago           4263.92
Columbus          3357.39
Springfield       2375.00
San Diego         2348.88
Name: Sales, dtype: float64

In [55]:
fig = px.bar(
    city_sales,
    title="Top 10 Cities by Sales"
)

fig.show()

## Insight

- New York City records the highest sales.
- Los Angeles is the second-highest contributing city.
- These cities should be prioritized for inventory allocation and marketing campaigns.

Monthly Sales Trend

In [56]:
monthly_sales = (
    df.groupby("Order Month")["Sales"]
      .sum()
)

monthly_sales

Order Month
1      5583.00
2      3933.52
3      9562.14
4      8910.66
5     10507.20
6      9733.69
7      9923.05
8     10217.75
9     19369.70
10    12161.87
11    20646.57
12    21234.48
Name: Sales, dtype: float64

In [57]:
fig = px.line(
    monthly_sales,
    title="Monthly Sales Trend",
    markers=True
)

fig.show()

## Insight

- Sales gradually increase throughout the year.
- A significant increase is observed during the final quarter.
- Demand peaks in November and December, indicating seasonal sales growth.

Correlation Heatmap

In [58]:
import plotly.express as px

corr = df[["Sales", "Gross Profit", "Cost", "Units", "Lead Time"]].corr()

fig = px.imshow(
    corr,
    text_auto=True,
    title="Correlation Heatmap"
)

fig.show()

## Insight

- Sales and Gross Profit have a very strong positive correlation.
- Sales and Cost are also highly correlated.
- Lead Time has very little correlation with sales and profit, suggesting delivery time does not significantly influence revenue.